$axure.loadCurrentPage({
  "url":"系统设置.html",
  "generationDate":new Date(1418135181764.36),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dff9e6dafe93444b98750fbe687a809f",
    "type":"Axure:Page",
    "name":"系统设置",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b5cdff0db7a14a93ad777f5b072152cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":60,
              "y":0},
            "size":{
              "width":1001,
              "height":1320},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"675f103866be49ecb3e3b4b05e747c1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":60,
                  "y":0},
                "size":{
                  "width":1001,
                  "height":1320},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统设置/u0.png"}},
{
          "id":"a935047358ce4202a08f9a09d088187b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":26},
            "size":{
              "width":1000,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d79074d47684497be730aad5fe5c47f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":26},
                "size":{
                  "width":1000,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-游客/u4.jpg"}},
{
          "id":"6ce3b2fab5fc48bf969b283ca20af3df",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":961,
              "y":41},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2415373d0f146edad983ca30ec406cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":961,
                  "y":41},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-会员",
                      "target":{
                        "targetType":"page",
                        "url":"首页-会员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-游客/u6.png"}},
{
          "id":"ba7d787947784c9da90880c36812da4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'楷体 Regular', '楷体'",
            "fontSize":"16px",
            "location":{
              "x":61,
              "y":0},
            "size":{
              "width":100,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b0a52e8433941ecac6d9ed4fb76d51e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'楷体 Regular', '楷体'",
                "fontSize":"16px",
                "location":{
                  "x":61,
                  "y":0},
                "size":{
                  "width":100,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a484fb1997eb427190cd78022f4f1e13",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"bold"}},
            "location":{
              "x":138,
              "y":0},
            "size":{
              "width":72,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"425f390f91974824bf1180d898d54d16",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"bold"}},
                "location":{
                  "x":138,
                  "y":0},
                "size":{
                  "width":72,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SystemManager",
                      "target":{
                        "targetType":"page",
                        "url":"systemmanager.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"7d2540c45516451db3919d99fbe35e93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "location":{
              "x":1001,
              "y":0},
            "size":{
              "width":60,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b42716ab74f475492a2fbf9303b0062",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":1001,
                  "y":0},
                "size":{
                  "width":60,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"732d43712c164292b76fd57743b14a8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xEF00FFFF},
{
                  "color":0xEF00FFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":61,
              "y":200},
            "size":{
              "width":1000,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9e987910dca4255a36da2a27c129b9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xEF00FFFF},
{
                      "color":0xEF00FFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":61,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/systemmanager/u12.png"}},
{
          "id":"0b9a3beaa45a49168cdc00a648dafc44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":101,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d6d30076acd4eb9a57e29e37426964e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":101,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 用户管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"2c222e2c00d64589ae1bbc53535ebf34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":231,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2538a4ed5f3e4964b5929a09fb39c9d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":231,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 数据备份 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"数据备份.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"56d958fa352642d19853c6054397e5b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":361,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca802e86ba584efb908d109984cfb4ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":361,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 日志管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"日志管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"33856c491ac14fefb6e8b762f9e68414",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":501,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa1275c67a494552aeb7ece2a5e5433f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":501,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 广告管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"广告管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"40d631e5e50b492a994d9241c7ae1739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":641,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"703da5f5afa54a7983278dfb5d89f897",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":641,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 系统设置 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户管理/u14.png",
            "mouseOver~":"images/用户管理/u14.png"}},
{
          "id":"89ddbe942ff9466b9c0b0118808794cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":781,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"968c375f39b14c29ae38eabdf28fd8f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":781,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 权限管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"权限管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"e31770f265ae45ecae57ba7f25eb1e56",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCDE7E7},
            "location":{
              "x":90,
              "y":270},
            "size":{
              "width":940,
              "height":740},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b5d250242b0e46cf8a4b2a4c3f861bce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCDE7E7},
                "location":{
                  "x":90,
                  "y":270},
                "size":{
                  "width":940,
                  "height":740},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统设置/u26.png"}},
{
          "id":"258b341027da4079ba2f7c825030e846",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "location":{
              "x":205,
              "y":0},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7af572675cf4365bb4231e3e06ec4ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":205,
                  "y":0},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 父窗口 打开 系统设置",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true},
                      "linkType":"parent"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"30b39f2d98b148bbb12cba69338823d2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":280,
              "y":372},
            "size":{
              "width":100,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"758c054c730d415dac6a7069c7aa27c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":280,
                  "y":372},
                "size":{
                  "width":100,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"134928b863544c0e880f0d436b3799b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":296},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afa17ec34f8f47ac9b509ffd91e8f353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":429,
                  "y":296},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-游客/u6.png"}},
{
          "id":"535d31b75efb474b874e6079238718e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":271,
              "y":474},
            "size":{
              "width":109,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe1fe6354f74b06974826e73b1bcc2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":271,
                  "y":474},
                "size":{
                  "width":109,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6750d5b311d24698887ad5cc3af796f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":271,
              "y":559},
            "size":{
              "width":129,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4efb71c56699489282a8e4224efeadcb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":271,
                  "y":559},
                "size":{
                  "width":129,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"263a93bf839d4f2c81207281279b6450",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":271,
              "y":646},
            "size":{
              "width":119,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83883300e0664e978bd3e577c8dd03dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":271,
                  "y":646},
                "size":{
                  "width":119,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08c378ad468948ccac8a4052ff9413dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":271,
              "y":847},
            "size":{
              "width":219,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b26520ce06f346409fc3674ad0e3781d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":271,
                  "y":847},
                "size":{
                  "width":219,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"898b065faf4c4956b817d0a1fcc85973",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":474},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4365d7542e3545029ea289903a6c683e",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":559},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"8efb935065f54499b435e65eb384249b",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "location":{
              "x":429,
              "y":646},
            "size":{
              "width":291,
              "height":144}},
          "adaptiveStyles":{
}},
{
          "id":"5ef143b7d6524e3180d7401a79c3bae4",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":846},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"b463180516df427a8a42907b15482585",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":935},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"7f924bfcb52c4a0cb467ce0b20a06d05",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":510,
              "y":935},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9cfc77a6f4de4e2592904f7a3850696d",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":62,
              "y":1060}},
          "adaptiveStyles":{
},
          "masterId":"2bc24d6aa37f48fca27a2edc2566f219"}]}},
  "masters":{
    "2bc24d6aa37f48fca27a2edc2566f219":{
      "packageId":"2bc24d6aa37f48fca27a2edc2566f219",
      "type":"Axure:Master",
      "name":"尾部-母版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b9d9dbc456e54e4d8e0abd9bea476253",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":392,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59080c0d83704c0ca781e25ed4e01da8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":392,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e45799983cc94366b9bb4f8c703c4194",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":210},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f57e5c6eca1544e58ea3e8ff7e56ad34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":362,
                    "y":210},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-游客/u6.png"}},
{
            "id":"4deba176ee9e43789560c141124c9986",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":310,
                "y":54},
              "size":{
                "width":73,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7ab3558d7a24cad9d978fe12fc15f9e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":310,
                    "y":54},
                  "size":{
                    "width":73,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4d40de7299a248dabd09cef5878a0f1e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.647058823529412}},
                  "outerShadow":{
                    "on":true,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":314,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44eb0254c92943879cacad1d8352d8a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":0,
                          "g":0,
                          "b":0,
                          "a":0.647058823529412}},
                      "outerShadow":{
                        "on":true,
                        "offsetX":5,
                        "offsetY":5,
                        "blurRadius":5,
                        "color":{
                          "r":0,
                          "g":0,
                          "b":0,
                          "a":0.349019607843137}}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":314,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkFrame",
                        "description":"打开 美食推荐 在父窗口",
                        "linkType":"parentFrame",
                        "target":{
                          "targetType":"page",
                          "url":"美食推荐.html",
                          "includeVariables":true}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"6dcc822e1adb4096af53c02c36d3cb3b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":314,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f79e528090e412e9e5882aaa3fe552e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":314,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"60c82841d7054aacbf2e670de65dbeaa",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":314,
                "y":152},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53647476ac6446df845bc73a42866610",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":314,
                    "y":152},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0c1ff6fccc464720af4e56c993bd89d7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":450,
                "y":54},
              "size":{
                "width":109,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4856d3b8fe6243848452ebbfa233f8de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":450,
                    "y":54},
                  "size":{
                    "width":109,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"03038279fe4940c584406df1e5d06edb",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":94},
              "size":{
                "width":53,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5431d81553824e8596db7ffc72f129ad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":94},
                  "size":{
                    "width":53,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b84ad7cf7bf842e7a1256abb17aff0a1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":122},
              "size":{
                "width":98,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ceb6fa7056047c1a833a85954b9e528",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":122},
                  "size":{
                    "width":98,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce410b98cc7945bf8614cc73c1cc88af",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":152},
              "size":{
                "width":104,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"849721af33b64096bea60756168df0ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":152},
                  "size":{
                    "width":104,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0b8272a768ba45248007fd9163a38922",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":632,
                "y":54},
              "size":{
                "width":86,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4432ce471bc942ab8f1b36461fbe1b8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":632,
                    "y":54},
                  "size":{
                    "width":86,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"858970f3895140cbba2b7764cb7b89df",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eeb783473ff6445a94e311685a4342db",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f3b6916191894d8b81b7424d3e9045e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa669e2b318041caa10ecb5ce8d87ab1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"474b1470cbf1451587e4baadbe552f35",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":152},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c637fde17bcd4bd5bc986d5c86d66dec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":152},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f8ddfc2ca45e43928f0ecb94bb40d504",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":814,
                "y":54},
              "size":{
                "width":73,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"079f45a243424581aa27074b6a540345",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":814,
                    "y":54},
                  "size":{
                    "width":73,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"646c844975414d0ba7ffb19e35a4fd24",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":814,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ffb6eb232ab4ed68658a4fd03e996a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":814,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7897f701f1404f0a8e0d113030524e65",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":814,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"38cb138dc8754ae3b80d3ef25d025090",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":814,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"69988047564d4a0d919e20f85f024384",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":472,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"405ce975c8a548e2ba228f7ec8a28f57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":472,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ebf7f39846c741e2b30ca34abd559f94",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":558,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b030ec32c43946eca2bc7113a7765a72",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":558,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"48f6d60726ce400b974fcdefb50a5da4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":642,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c37f2721da934703ac3f4b89684ff202",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":642,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78a2f98174e24fa7a7ca5386815c9cd7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":734,
                "y":214},
              "size":{
                "width":97,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"348e775cfdf242ab8fc1f78b325f5b90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":734,
                    "y":214},
                  "size":{
                    "width":97,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4427c544919f48eeb68d4a1fc70fc896",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":200,
                "y":258},
              "size":{
                "width":248,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf758ab4dc194b1aadb7d769c5178f34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":200,
                    "y":258},
                  "size":{
                    "width":248,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b849ec93d5744852b6b806c12e38351b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":486,
                "y":258},
              "size":{
                "width":145,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"786f18d4bdf2439b90764113463224cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":486,
                    "y":258},
                  "size":{
                    "width":145,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7107dfd844e4d838b4dd468406982af",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":670,
                "y":258},
              "size":{
                "width":240,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a12ed323c09c40298ad5950c9617ffe1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":670,
                    "y":258},
                  "size":{
                    "width":240,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c57f4b97c75b49039a289fe069949b12",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":940,
                "y":258},
              "size":{
                "width":100,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7d340984ce3241419a70e2dbbdf6666f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":940,
                    "y":258},
                  "size":{
                    "width":100,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a8fc1a806536415abbaef0f5c602a689",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.8",
              "location":{
                "x":122,
                "y":30},
              "size":{
                "width":998,
                "height":10},
              "borderWidth":"4",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u250_line.png"}},
{
            "id":"eaaafc313b134f8f8524fa334162f922",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":200,
                "y":191},
              "size":{
                "width":840,
                "height":10},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u251_line.png"}},
{
            "id":"7aa4994dce524c92906c252006d25e06",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":419,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}},
{
            "id":"3996e23147554ca0b6327f6c767b2661",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":585,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}},
{
            "id":"7996e335f69441238f1d42f1eef188b1",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":759,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}}]}}},
  "objectPaths":{
    "b5cdff0db7a14a93ad777f5b072152cb":{
      "scriptId":"u0"},
    "675f103866be49ecb3e3b4b05e747c1d":{
      "scriptId":"u1"},
    "a935047358ce4202a08f9a09d088187b":{
      "scriptId":"u2"},
    "2d79074d47684497be730aad5fe5c47f":{
      "scriptId":"u3"},
    "6ce3b2fab5fc48bf969b283ca20af3df":{
      "scriptId":"u4"},
    "c2415373d0f146edad983ca30ec406cc":{
      "scriptId":"u5"},
    "ba7d787947784c9da90880c36812da4c":{
      "scriptId":"u6"},
    "5b0a52e8433941ecac6d9ed4fb76d51e":{
      "scriptId":"u7"},
    "a484fb1997eb427190cd78022f4f1e13":{
      "scriptId":"u8"},
    "425f390f91974824bf1180d898d54d16":{
      "scriptId":"u9"},
    "7d2540c45516451db3919d99fbe35e93":{
      "scriptId":"u10"},
    "5b42716ab74f475492a2fbf9303b0062":{
      "scriptId":"u11"},
    "732d43712c164292b76fd57743b14a8b":{
      "scriptId":"u12"},
    "a9e987910dca4255a36da2a27c129b9e":{
      "scriptId":"u13"},
    "0b9a3beaa45a49168cdc00a648dafc44":{
      "scriptId":"u14"},
    "3d6d30076acd4eb9a57e29e37426964e":{
      "scriptId":"u15"},
    "2c222e2c00d64589ae1bbc53535ebf34":{
      "scriptId":"u16"},
    "2538a4ed5f3e4964b5929a09fb39c9d4":{
      "scriptId":"u17"},
    "56d958fa352642d19853c6054397e5b3":{
      "scriptId":"u18"},
    "ca802e86ba584efb908d109984cfb4ae":{
      "scriptId":"u19"},
    "33856c491ac14fefb6e8b762f9e68414":{
      "scriptId":"u20"},
    "aa1275c67a494552aeb7ece2a5e5433f":{
      "scriptId":"u21"},
    "40d631e5e50b492a994d9241c7ae1739":{
      "scriptId":"u22"},
    "703da5f5afa54a7983278dfb5d89f897":{
      "scriptId":"u23"},
    "89ddbe942ff9466b9c0b0118808794cd":{
      "scriptId":"u24"},
    "968c375f39b14c29ae38eabdf28fd8f4":{
      "scriptId":"u25"},
    "e31770f265ae45ecae57ba7f25eb1e56":{
      "scriptId":"u26"},
    "b5d250242b0e46cf8a4b2a4c3f861bce":{
      "scriptId":"u27"},
    "258b341027da4079ba2f7c825030e846":{
      "scriptId":"u28"},
    "a7af572675cf4365bb4231e3e06ec4ec":{
      "scriptId":"u29"},
    "30b39f2d98b148bbb12cba69338823d2":{
      "scriptId":"u30"},
    "758c054c730d415dac6a7069c7aa27c8":{
      "scriptId":"u31"},
    "134928b863544c0e880f0d436b3799b0":{
      "scriptId":"u32"},
    "afa17ec34f8f47ac9b509ffd91e8f353":{
      "scriptId":"u33"},
    "535d31b75efb474b874e6079238718e8":{
      "scriptId":"u34"},
    "afe1fe6354f74b06974826e73b1bcc2c":{
      "scriptId":"u35"},
    "6750d5b311d24698887ad5cc3af796f7":{
      "scriptId":"u36"},
    "4efb71c56699489282a8e4224efeadcb":{
      "scriptId":"u37"},
    "263a93bf839d4f2c81207281279b6450":{
      "scriptId":"u38"},
    "83883300e0664e978bd3e577c8dd03dd":{
      "scriptId":"u39"},
    "08c378ad468948ccac8a4052ff9413dd":{
      "scriptId":"u40"},
    "b26520ce06f346409fc3674ad0e3781d":{
      "scriptId":"u41"},
    "898b065faf4c4956b817d0a1fcc85973":{
      "scriptId":"u42"},
    "4365d7542e3545029ea289903a6c683e":{
      "scriptId":"u43"},
    "8efb935065f54499b435e65eb384249b":{
      "scriptId":"u44"},
    "5ef143b7d6524e3180d7401a79c3bae4":{
      "scriptId":"u45"},
    "b463180516df427a8a42907b15482585":{
      "scriptId":"u46"},
    "7f924bfcb52c4a0cb467ce0b20a06d05":{
      "scriptId":"u47"},
    "9cfc77a6f4de4e2592904f7a3850696d":{
      "scriptId":"u48",
      "b9d9dbc456e54e4d8e0abd9bea476253":{
        "scriptId":"u49"},
      "59080c0d83704c0ca781e25ed4e01da8":{
        "scriptId":"u50"},
      "e45799983cc94366b9bb4f8c703c4194":{
        "scriptId":"u51"},
      "f57e5c6eca1544e58ea3e8ff7e56ad34":{
        "scriptId":"u52"},
      "4deba176ee9e43789560c141124c9986":{
        "scriptId":"u53"},
      "e7ab3558d7a24cad9d978fe12fc15f9e":{
        "scriptId":"u54"},
      "4d40de7299a248dabd09cef5878a0f1e":{
        "scriptId":"u55"},
      "44eb0254c92943879cacad1d8352d8a8":{
        "scriptId":"u56"},
      "6dcc822e1adb4096af53c02c36d3cb3b":{
        "scriptId":"u57"},
      "1f79e528090e412e9e5882aaa3fe552e":{
        "scriptId":"u58"},
      "60c82841d7054aacbf2e670de65dbeaa":{
        "scriptId":"u59"},
      "53647476ac6446df845bc73a42866610":{
        "scriptId":"u60"},
      "0c1ff6fccc464720af4e56c993bd89d7":{
        "scriptId":"u61"},
      "4856d3b8fe6243848452ebbfa233f8de":{
        "scriptId":"u62"},
      "03038279fe4940c584406df1e5d06edb":{
        "scriptId":"u63"},
      "5431d81553824e8596db7ffc72f129ad":{
        "scriptId":"u64"},
      "b84ad7cf7bf842e7a1256abb17aff0a1":{
        "scriptId":"u65"},
      "7ceb6fa7056047c1a833a85954b9e528":{
        "scriptId":"u66"},
      "ce410b98cc7945bf8614cc73c1cc88af":{
        "scriptId":"u67"},
      "849721af33b64096bea60756168df0ce":{
        "scriptId":"u68"},
      "0b8272a768ba45248007fd9163a38922":{
        "scriptId":"u69"},
      "4432ce471bc942ab8f1b36461fbe1b8f":{
        "scriptId":"u70"},
      "858970f3895140cbba2b7764cb7b89df":{
        "scriptId":"u71"},
      "eeb783473ff6445a94e311685a4342db":{
        "scriptId":"u72"},
      "f3b6916191894d8b81b7424d3e9045e7":{
        "scriptId":"u73"},
      "aa669e2b318041caa10ecb5ce8d87ab1":{
        "scriptId":"u74"},
      "474b1470cbf1451587e4baadbe552f35":{
        "scriptId":"u75"},
      "c637fde17bcd4bd5bc986d5c86d66dec":{
        "scriptId":"u76"},
      "f8ddfc2ca45e43928f0ecb94bb40d504":{
        "scriptId":"u77"},
      "079f45a243424581aa27074b6a540345":{
        "scriptId":"u78"},
      "646c844975414d0ba7ffb19e35a4fd24":{
        "scriptId":"u79"},
      "6ffb6eb232ab4ed68658a4fd03e996a8":{
        "scriptId":"u80"},
      "7897f701f1404f0a8e0d113030524e65":{
        "scriptId":"u81"},
      "38cb138dc8754ae3b80d3ef25d025090":{
        "scriptId":"u82"},
      "69988047564d4a0d919e20f85f024384":{
        "scriptId":"u83"},
      "405ce975c8a548e2ba228f7ec8a28f57":{
        "scriptId":"u84"},
      "ebf7f39846c741e2b30ca34abd559f94":{
        "scriptId":"u85"},
      "b030ec32c43946eca2bc7113a7765a72":{
        "scriptId":"u86"},
      "48f6d60726ce400b974fcdefb50a5da4":{
        "scriptId":"u87"},
      "c37f2721da934703ac3f4b89684ff202":{
        "scriptId":"u88"},
      "78a2f98174e24fa7a7ca5386815c9cd7":{
        "scriptId":"u89"},
      "348e775cfdf242ab8fc1f78b325f5b90":{
        "scriptId":"u90"},
      "4427c544919f48eeb68d4a1fc70fc896":{
        "scriptId":"u91"},
      "cf758ab4dc194b1aadb7d769c5178f34":{
        "scriptId":"u92"},
      "b849ec93d5744852b6b806c12e38351b":{
        "scriptId":"u93"},
      "786f18d4bdf2439b90764113463224cc":{
        "scriptId":"u94"},
      "e7107dfd844e4d838b4dd468406982af":{
        "scriptId":"u95"},
      "a12ed323c09c40298ad5950c9617ffe1":{
        "scriptId":"u96"},
      "c57f4b97c75b49039a289fe069949b12":{
        "scriptId":"u97"},
      "7d340984ce3241419a70e2dbbdf6666f":{
        "scriptId":"u98"},
      "a8fc1a806536415abbaef0f5c602a689":{
        "scriptId":"u99"},
      "eaaafc313b134f8f8524fa334162f922":{
        "scriptId":"u100"},
      "7aa4994dce524c92906c252006d25e06":{
        "scriptId":"u101"},
      "3996e23147554ca0b6327f6c767b2661":{
        "scriptId":"u102"},
      "7996e335f69441238f1d42f1eef188b1":{
        "scriptId":"u103"}}}});