$axure.loadCurrentPage({
  "url":"systemmanager.html",
  "generationDate":new Date(1418135177893.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d4ed7808c3894d6d861315bbb78f7af5",
    "type":"Axure:Page",
    "name":"SystemManager",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b0ce2123eda0420787a8215febbfc1ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":60,
              "y":0},
            "size":{
              "width":1001,
              "height":920},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76b76efefceb480dbba3a6c313cda435",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":60,
                  "y":0},
                "size":{
                  "width":1001,
                  "height":920},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/systemmanager/u0.png"}},
{
          "id":"15809561aca345e3a278fd747ea87b1d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":26},
            "size":{
              "width":1000,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c15fac7cd08430891a3fcc8d8845199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":26},
                "size":{
                  "width":1000,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-游客/u4.jpg"}},
{
          "id":"0396b843da924d85b09ae71c4e4722a5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":961,
              "y":41},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef60cc2db35d46739eb68c047fd650b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":961,
                  "y":41},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-会员",
                      "target":{
                        "targetType":"page",
                        "url":"首页-会员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-游客/u6.png"}},
{
          "id":"92e1be9072e042deb8fc7c760ef042f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'楷体 Regular', '楷体'",
            "fontSize":"18px",
            "location":{
              "x":61,
              "y":0},
            "size":{
              "width":100,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1589a289738e4b3fb748a2e080b57c70",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'楷体 Regular', '楷体'",
                "fontSize":"18px",
                "location":{
                  "x":61,
                  "y":0},
                "size":{
                  "width":100,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2a8310cef6f24ca4995663f3817091cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"bold"}},
            "location":{
              "x":151,
              "y":0},
            "size":{
              "width":110,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdfccec0c6184b8ab4d08d9d6f42130c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"bold"}},
                "location":{
                  "x":151,
                  "y":0},
                "size":{
                  "width":110,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 重新加载",
                      "target":{
                        "targetType":"reloadPage",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"99881ff73cb54c2698f210ff055427a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "location":{
              "x":1001,
              "y":0},
            "size":{
              "width":60,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c849b99345da4518ae1425d070c98a05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":1001,
                  "y":0},
                "size":{
                  "width":60,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"1bf2cec3ab4d4e44955a5a2fd1058837",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xEF00FFFF},
{
                  "color":0xEF00FFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":61,
              "y":200},
            "size":{
              "width":1000,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b562a463c8043b481623df044bd40ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xEF00FFFF},
{
                      "color":0xEF00FFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":61,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/systemmanager/u12.png"}},
{
          "id":"22672833bdb64401b7d9a6894aed3908",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":101,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c32a4950f8654a52a718cab6acca1009",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":101,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 用户管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"09aa8e5fb8f246e79f2e313e6eac00c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":231,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba50168708894530971249780cca76be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":231,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 数据备份 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"数据备份.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"479261fd3d63413a83ab2c165b81b4bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":361,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae49a4d082d14e55bb077983e599877b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":361,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 日志管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"日志管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"f6215eaa7ea348fe9a19f79075abe877",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":501,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5949ad8704aa4f9f9e7f2e2def3c672a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":501,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 广告管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"广告管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"63773908e4064064a68102de52a40193",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":641,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c56be9c1c39e47a1b0bdcc5729073553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":641,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 系统设置 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"18e4dd2a5710448d81eb5280d4ece24f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":781,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7588e50f0a04215bb1f3da582204adb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":781,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 权限管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"权限管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"4a3746e4b5da47e0b28810918d6cb5f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF66CCCC},
            "location":{
              "x":91,
              "y":270},
            "size":{
              "width":940,
              "height":310},
            "linePattern":"none",
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"529e14a80458412aa8685b10e0bb1b75",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF66CCCC},
                "location":{
                  "x":91,
                  "y":270},
                "size":{
                  "width":940,
                  "height":310},
                "linePattern":"none",
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/systemmanager/u26.png"}},
{
          "id":"eafdce8a378e4f4bb919ed9d90139fb1",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0033FF},
{
                  "color":0xFF0033FF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":90,
              "y":270},
            "size":{
              "width":940,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fac36d636eea4fabb6a4e3971a1ff346",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0033FF},
{
                      "color":0xFF0033FF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":90,
                  "y":270},
                "size":{
                  "width":940,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/systemmanager/u28.png"}},
{
          "id":"f702b12fc44f456f8adaad7a25d53b4f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0033FF},
{
                  "color":0xFF0033FF},
{
                  "color":0xFFE4E4E4},
{
                  "color":0xFFE4E4E4}]},
            "location":{
              "x":90,
              "y":550},
            "size":{
              "width":940,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2916fd226db4eb5b48bab4a29448c8e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0033FF},
{
                      "color":0xFF0033FF},
{
                      "color":0xFFE4E4E4},
{
                      "color":0xFFE4E4E4}]},
                "location":{
                  "x":90,
                  "y":550},
                "size":{
                  "width":940,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/systemmanager/u30.png"}},
{
          "id":"3da8ec97f8a0447a82a6b1b0b86f3fc3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'方正舒体 Regular', '方正舒体'",
            "fontSize":"48px",
            "location":{
              "x":348,
              "y":370},
            "size":{
              "width":393,
              "height":51}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f8c7218847e4ec29b65faabbd611e28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'方正舒体 Regular', '方正舒体'",
                "fontSize":"48px",
                "location":{
                  "x":348,
                  "y":370},
                "size":{
                  "width":393,
                  "height":51}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 用户管理",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1073b7596d445058582ba10c01a37b3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1}}},
            "location":{
              "x":489,
              "y":454},
            "size":{
              "width":100,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f2aeea0350a401ab2d09ac01d1e18ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0000FF,
                      "opacity":1}}},
                "location":{
                  "x":489,
                  "y":454},
                "size":{
                  "width":100,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 弹出窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"popup",
                      "popup":{
                        "left":100,
                        "top":100,
                        "width":500,
                        "height":500,
                        "toolbar":false,
                        "scrollbars":false,
                        "location":false,
                        "status":false,
                        "menubar":false,
                        "directories":false,
                        "resizable":false,
                        "centerwindow":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"4e99a521f1404970a578e7d410433429",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":666}},
          "adaptiveStyles":{
},
          "masterId":"2bc24d6aa37f48fca27a2edc2566f219"}]}},
  "masters":{
    "2bc24d6aa37f48fca27a2edc2566f219":{
      "packageId":"2bc24d6aa37f48fca27a2edc2566f219",
      "type":"Axure:Master",
      "name":"尾部-母版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b9d9dbc456e54e4d8e0abd9bea476253",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":392,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59080c0d83704c0ca781e25ed4e01da8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":392,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e45799983cc94366b9bb4f8c703c4194",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":210},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f57e5c6eca1544e58ea3e8ff7e56ad34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":362,
                    "y":210},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-游客/u6.png"}},
{
            "id":"4deba176ee9e43789560c141124c9986",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":310,
                "y":54},
              "size":{
                "width":73,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7ab3558d7a24cad9d978fe12fc15f9e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":310,
                    "y":54},
                  "size":{
                    "width":73,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4d40de7299a248dabd09cef5878a0f1e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.647058823529412}},
                  "outerShadow":{
                    "on":true,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":314,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44eb0254c92943879cacad1d8352d8a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":0,
                          "g":0,
                          "b":0,
                          "a":0.647058823529412}},
                      "outerShadow":{
                        "on":true,
                        "offsetX":5,
                        "offsetY":5,
                        "blurRadius":5,
                        "color":{
                          "r":0,
                          "g":0,
                          "b":0,
                          "a":0.349019607843137}}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":314,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkFrame",
                        "description":"打开 美食推荐 在父窗口",
                        "linkType":"parentFrame",
                        "target":{
                          "targetType":"page",
                          "url":"美食推荐.html",
                          "includeVariables":true}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"6dcc822e1adb4096af53c02c36d3cb3b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":314,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f79e528090e412e9e5882aaa3fe552e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":314,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"60c82841d7054aacbf2e670de65dbeaa",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":314,
                "y":152},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53647476ac6446df845bc73a42866610",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":314,
                    "y":152},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0c1ff6fccc464720af4e56c993bd89d7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":450,
                "y":54},
              "size":{
                "width":109,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4856d3b8fe6243848452ebbfa233f8de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":450,
                    "y":54},
                  "size":{
                    "width":109,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"03038279fe4940c584406df1e5d06edb",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":94},
              "size":{
                "width":53,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5431d81553824e8596db7ffc72f129ad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":94},
                  "size":{
                    "width":53,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b84ad7cf7bf842e7a1256abb17aff0a1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":122},
              "size":{
                "width":98,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ceb6fa7056047c1a833a85954b9e528",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":122},
                  "size":{
                    "width":98,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce410b98cc7945bf8614cc73c1cc88af",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":152},
              "size":{
                "width":104,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"849721af33b64096bea60756168df0ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":152},
                  "size":{
                    "width":104,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0b8272a768ba45248007fd9163a38922",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":632,
                "y":54},
              "size":{
                "width":86,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4432ce471bc942ab8f1b36461fbe1b8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":632,
                    "y":54},
                  "size":{
                    "width":86,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"858970f3895140cbba2b7764cb7b89df",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eeb783473ff6445a94e311685a4342db",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f3b6916191894d8b81b7424d3e9045e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa669e2b318041caa10ecb5ce8d87ab1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"474b1470cbf1451587e4baadbe552f35",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":152},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c637fde17bcd4bd5bc986d5c86d66dec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":152},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f8ddfc2ca45e43928f0ecb94bb40d504",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":814,
                "y":54},
              "size":{
                "width":73,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"079f45a243424581aa27074b6a540345",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":814,
                    "y":54},
                  "size":{
                    "width":73,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"646c844975414d0ba7ffb19e35a4fd24",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":814,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ffb6eb232ab4ed68658a4fd03e996a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":814,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7897f701f1404f0a8e0d113030524e65",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":814,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"38cb138dc8754ae3b80d3ef25d025090",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":814,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"69988047564d4a0d919e20f85f024384",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":472,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"405ce975c8a548e2ba228f7ec8a28f57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":472,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ebf7f39846c741e2b30ca34abd559f94",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":558,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b030ec32c43946eca2bc7113a7765a72",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":558,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"48f6d60726ce400b974fcdefb50a5da4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":642,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c37f2721da934703ac3f4b89684ff202",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":642,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78a2f98174e24fa7a7ca5386815c9cd7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":734,
                "y":214},
              "size":{
                "width":97,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"348e775cfdf242ab8fc1f78b325f5b90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":734,
                    "y":214},
                  "size":{
                    "width":97,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4427c544919f48eeb68d4a1fc70fc896",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":200,
                "y":258},
              "size":{
                "width":248,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf758ab4dc194b1aadb7d769c5178f34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":200,
                    "y":258},
                  "size":{
                    "width":248,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b849ec93d5744852b6b806c12e38351b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":486,
                "y":258},
              "size":{
                "width":145,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"786f18d4bdf2439b90764113463224cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":486,
                    "y":258},
                  "size":{
                    "width":145,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7107dfd844e4d838b4dd468406982af",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":670,
                "y":258},
              "size":{
                "width":240,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a12ed323c09c40298ad5950c9617ffe1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":670,
                    "y":258},
                  "size":{
                    "width":240,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c57f4b97c75b49039a289fe069949b12",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":940,
                "y":258},
              "size":{
                "width":100,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7d340984ce3241419a70e2dbbdf6666f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":940,
                    "y":258},
                  "size":{
                    "width":100,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a8fc1a806536415abbaef0f5c602a689",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.8",
              "location":{
                "x":122,
                "y":30},
              "size":{
                "width":998,
                "height":10},
              "borderWidth":"4",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u250_line.png"}},
{
            "id":"eaaafc313b134f8f8524fa334162f922",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":200,
                "y":191},
              "size":{
                "width":840,
                "height":10},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u251_line.png"}},
{
            "id":"7aa4994dce524c92906c252006d25e06",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":419,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}},
{
            "id":"3996e23147554ca0b6327f6c767b2661",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":585,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}},
{
            "id":"7996e335f69441238f1d42f1eef188b1",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":759,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}}]}}},
  "objectPaths":{
    "b0ce2123eda0420787a8215febbfc1ab":{
      "scriptId":"u0"},
    "76b76efefceb480dbba3a6c313cda435":{
      "scriptId":"u1"},
    "15809561aca345e3a278fd747ea87b1d":{
      "scriptId":"u2"},
    "8c15fac7cd08430891a3fcc8d8845199":{
      "scriptId":"u3"},
    "0396b843da924d85b09ae71c4e4722a5":{
      "scriptId":"u4"},
    "ef60cc2db35d46739eb68c047fd650b4":{
      "scriptId":"u5"},
    "92e1be9072e042deb8fc7c760ef042f0":{
      "scriptId":"u6"},
    "1589a289738e4b3fb748a2e080b57c70":{
      "scriptId":"u7"},
    "2a8310cef6f24ca4995663f3817091cc":{
      "scriptId":"u8"},
    "cdfccec0c6184b8ab4d08d9d6f42130c":{
      "scriptId":"u9"},
    "99881ff73cb54c2698f210ff055427a7":{
      "scriptId":"u10"},
    "c849b99345da4518ae1425d070c98a05":{
      "scriptId":"u11"},
    "1bf2cec3ab4d4e44955a5a2fd1058837":{
      "scriptId":"u12"},
    "6b562a463c8043b481623df044bd40ef":{
      "scriptId":"u13"},
    "22672833bdb64401b7d9a6894aed3908":{
      "scriptId":"u14"},
    "c32a4950f8654a52a718cab6acca1009":{
      "scriptId":"u15"},
    "09aa8e5fb8f246e79f2e313e6eac00c9":{
      "scriptId":"u16"},
    "ba50168708894530971249780cca76be":{
      "scriptId":"u17"},
    "479261fd3d63413a83ab2c165b81b4bc":{
      "scriptId":"u18"},
    "ae49a4d082d14e55bb077983e599877b":{
      "scriptId":"u19"},
    "f6215eaa7ea348fe9a19f79075abe877":{
      "scriptId":"u20"},
    "5949ad8704aa4f9f9e7f2e2def3c672a":{
      "scriptId":"u21"},
    "63773908e4064064a68102de52a40193":{
      "scriptId":"u22"},
    "c56be9c1c39e47a1b0bdcc5729073553":{
      "scriptId":"u23"},
    "18e4dd2a5710448d81eb5280d4ece24f":{
      "scriptId":"u24"},
    "d7588e50f0a04215bb1f3da582204adb":{
      "scriptId":"u25"},
    "4a3746e4b5da47e0b28810918d6cb5f5":{
      "scriptId":"u26"},
    "529e14a80458412aa8685b10e0bb1b75":{
      "scriptId":"u27"},
    "eafdce8a378e4f4bb919ed9d90139fb1":{
      "scriptId":"u28"},
    "fac36d636eea4fabb6a4e3971a1ff346":{
      "scriptId":"u29"},
    "f702b12fc44f456f8adaad7a25d53b4f":{
      "scriptId":"u30"},
    "c2916fd226db4eb5b48bab4a29448c8e":{
      "scriptId":"u31"},
    "3da8ec97f8a0447a82a6b1b0b86f3fc3":{
      "scriptId":"u32"},
    "3f8c7218847e4ec29b65faabbd611e28":{
      "scriptId":"u33"},
    "e1073b7596d445058582ba10c01a37b3":{
      "scriptId":"u34"},
    "0f2aeea0350a401ab2d09ac01d1e18ff":{
      "scriptId":"u35"},
    "4e99a521f1404970a578e7d410433429":{
      "scriptId":"u36",
      "b9d9dbc456e54e4d8e0abd9bea476253":{
        "scriptId":"u37"},
      "59080c0d83704c0ca781e25ed4e01da8":{
        "scriptId":"u38"},
      "e45799983cc94366b9bb4f8c703c4194":{
        "scriptId":"u39"},
      "f57e5c6eca1544e58ea3e8ff7e56ad34":{
        "scriptId":"u40"},
      "4deba176ee9e43789560c141124c9986":{
        "scriptId":"u41"},
      "e7ab3558d7a24cad9d978fe12fc15f9e":{
        "scriptId":"u42"},
      "4d40de7299a248dabd09cef5878a0f1e":{
        "scriptId":"u43"},
      "44eb0254c92943879cacad1d8352d8a8":{
        "scriptId":"u44"},
      "6dcc822e1adb4096af53c02c36d3cb3b":{
        "scriptId":"u45"},
      "1f79e528090e412e9e5882aaa3fe552e":{
        "scriptId":"u46"},
      "60c82841d7054aacbf2e670de65dbeaa":{
        "scriptId":"u47"},
      "53647476ac6446df845bc73a42866610":{
        "scriptId":"u48"},
      "0c1ff6fccc464720af4e56c993bd89d7":{
        "scriptId":"u49"},
      "4856d3b8fe6243848452ebbfa233f8de":{
        "scriptId":"u50"},
      "03038279fe4940c584406df1e5d06edb":{
        "scriptId":"u51"},
      "5431d81553824e8596db7ffc72f129ad":{
        "scriptId":"u52"},
      "b84ad7cf7bf842e7a1256abb17aff0a1":{
        "scriptId":"u53"},
      "7ceb6fa7056047c1a833a85954b9e528":{
        "scriptId":"u54"},
      "ce410b98cc7945bf8614cc73c1cc88af":{
        "scriptId":"u55"},
      "849721af33b64096bea60756168df0ce":{
        "scriptId":"u56"},
      "0b8272a768ba45248007fd9163a38922":{
        "scriptId":"u57"},
      "4432ce471bc942ab8f1b36461fbe1b8f":{
        "scriptId":"u58"},
      "858970f3895140cbba2b7764cb7b89df":{
        "scriptId":"u59"},
      "eeb783473ff6445a94e311685a4342db":{
        "scriptId":"u60"},
      "f3b6916191894d8b81b7424d3e9045e7":{
        "scriptId":"u61"},
      "aa669e2b318041caa10ecb5ce8d87ab1":{
        "scriptId":"u62"},
      "474b1470cbf1451587e4baadbe552f35":{
        "scriptId":"u63"},
      "c637fde17bcd4bd5bc986d5c86d66dec":{
        "scriptId":"u64"},
      "f8ddfc2ca45e43928f0ecb94bb40d504":{
        "scriptId":"u65"},
      "079f45a243424581aa27074b6a540345":{
        "scriptId":"u66"},
      "646c844975414d0ba7ffb19e35a4fd24":{
        "scriptId":"u67"},
      "6ffb6eb232ab4ed68658a4fd03e996a8":{
        "scriptId":"u68"},
      "7897f701f1404f0a8e0d113030524e65":{
        "scriptId":"u69"},
      "38cb138dc8754ae3b80d3ef25d025090":{
        "scriptId":"u70"},
      "69988047564d4a0d919e20f85f024384":{
        "scriptId":"u71"},
      "405ce975c8a548e2ba228f7ec8a28f57":{
        "scriptId":"u72"},
      "ebf7f39846c741e2b30ca34abd559f94":{
        "scriptId":"u73"},
      "b030ec32c43946eca2bc7113a7765a72":{
        "scriptId":"u74"},
      "48f6d60726ce400b974fcdefb50a5da4":{
        "scriptId":"u75"},
      "c37f2721da934703ac3f4b89684ff202":{
        "scriptId":"u76"},
      "78a2f98174e24fa7a7ca5386815c9cd7":{
        "scriptId":"u77"},
      "348e775cfdf242ab8fc1f78b325f5b90":{
        "scriptId":"u78"},
      "4427c544919f48eeb68d4a1fc70fc896":{
        "scriptId":"u79"},
      "cf758ab4dc194b1aadb7d769c5178f34":{
        "scriptId":"u80"},
      "b849ec93d5744852b6b806c12e38351b":{
        "scriptId":"u81"},
      "786f18d4bdf2439b90764113463224cc":{
        "scriptId":"u82"},
      "e7107dfd844e4d838b4dd468406982af":{
        "scriptId":"u83"},
      "a12ed323c09c40298ad5950c9617ffe1":{
        "scriptId":"u84"},
      "c57f4b97c75b49039a289fe069949b12":{
        "scriptId":"u85"},
      "7d340984ce3241419a70e2dbbdf6666f":{
        "scriptId":"u86"},
      "a8fc1a806536415abbaef0f5c602a689":{
        "scriptId":"u87"},
      "eaaafc313b134f8f8524fa334162f922":{
        "scriptId":"u88"},
      "7aa4994dce524c92906c252006d25e06":{
        "scriptId":"u89"},
      "3996e23147554ca0b6327f6c767b2661":{
        "scriptId":"u90"},
      "7996e335f69441238f1d42f1eef188b1":{
        "scriptId":"u91"}}}});