$axure.loadCurrentPage({
  "url":"数据备份.html",
  "generationDate":new Date(1418135179533.11),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a369abd8babb4b248590bfeff34dddc7",
    "type":"Axure:Page",
    "name":"数据备份",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2176af3dcc6b470aa26421769c5b75ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.5",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":60,
              "y":0},
            "size":{
              "width":1001,
              "height":1330},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d08cece41a234f8e875e845c2870dc81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.5",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":60,
                  "y":0},
                "size":{
                  "width":1001,
                  "height":1330},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u0.png"}},
{
          "id":"280932a0e79f4e9590c4ba8a4501abec",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":26},
            "size":{
              "width":1000,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f0a3bd116fe4436b5fe000a5c721d5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":26},
                "size":{
                  "width":1000,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页-游客/u4.jpg"}},
{
          "id":"9b89ab49ff57434ca3f31a13a9c965fd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":961,
              "y":41},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94912384d2e4438aafb6fefdfd3ea6df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":961,
                  "y":41},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-会员",
                      "target":{
                        "targetType":"page",
                        "url":"首页-会员.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-游客/u6.png"}},
{
          "id":"b5192b38107248e79e7cd362c5258bfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'楷体 Regular', '楷体'",
            "fontSize":"16px",
            "location":{
              "x":61,
              "y":0},
            "size":{
              "width":100,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c8f7445edd44c5a954c6aa2a7dadf05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'楷体 Regular', '楷体'",
                "fontSize":"16px",
                "location":{
                  "x":61,
                  "y":0},
                "size":{
                  "width":100,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3643f3c6ab734ad2ad7d779797c23b3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontWeight":"bold"}},
            "location":{
              "x":138,
              "y":0},
            "size":{
              "width":72,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"319801cc0ce543deb6f3e1caedac8648",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Arial Normal', 'Arial'",
                    "fontWeight":"bold"}},
                "location":{
                  "x":138,
                  "y":0},
                "size":{
                  "width":72,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 SystemManager",
                      "target":{
                        "targetType":"page",
                        "url":"systemmanager.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"1fd2e35b7a354e6d83f08d9ab6d3745b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "location":{
              "x":1001,
              "y":0},
            "size":{
              "width":60,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"670999e84a36439d83f2d3ed91667216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":1001,
                  "y":0},
                "size":{
                  "width":60,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"12f2b1721bdf475eae5dde7d3526e056",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xEF00FFFF},
{
                  "color":0xEF00FFFF},
{
                  "color":0xFF000000},
{
                  "color":0xFF000000}]},
            "location":{
              "x":61,
              "y":200},
            "size":{
              "width":1000,
              "height":40},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eda28cab72244b2f8c0e2c2c51983c8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xEF00FFFF},
{
                      "color":0xEF00FFFF},
{
                      "color":0xFF000000},
{
                      "color":0xFF000000}]},
                "location":{
                  "x":61,
                  "y":200},
                "size":{
                  "width":1000,
                  "height":40},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/systemmanager/u12.png"}},
{
          "id":"9ae3bcaac9a3466490f9e82b739ae48e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":101,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a009617fbaba49769851bc00a6d33aab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":101,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 用户管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"用户管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"9358afabecad4879a51dab02e5a54ccb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":231,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8325515690a442eb14910ce9ea1687a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":231,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 数据备份 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"数据备份.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/用户管理/u14.png",
            "mouseOver~":"images/用户管理/u14.png"}},
{
          "id":"27c0d8e7bd1441e0926d1e0d312753ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":361,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cb032d78c6a43498e895e7332b5341b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":361,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 日志管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"日志管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a51752e636dd430386934d9b34ec6ca5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":501,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eac24f15bf348f08f28279230e338fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":501,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 广告管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"广告管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"65ec34770a2d423d9995510b3cbac591",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":641,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d111526c60f34744a8c59791ee320284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":641,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 系统设置 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"系统设置.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"fbb65d6a4f254a7fbc190c21646eb499",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":781,
              "y":210},
            "size":{
              "width":100,
              "height":30},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93b90080a7ff4fa7acea3ce38d74cf67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0033FF,
                      "opacity":1}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":781,
                  "y":210},
                "size":{
                  "width":100,
                  "height":30},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkFrame",
                      "description":"打开 权限管理 在父窗口",
                      "linkType":"parentFrame",
                      "target":{
                        "targetType":"page",
                        "url":"权限管理.html",
                        "includeVariables":true}}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"ddf248c3d8ce4d79a32f9611f83bb581",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'仿宋 Regular', '仿宋'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fontWeight":"bold"}},
            "location":{
              "x":205,
              "y":0},
            "size":{
              "width":80,
              "height":18}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70136e6c00ad4c0195ea1c8a29d6235d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'仿宋 Regular', '仿宋'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fontWeight":"bold"}},
                "location":{
                  "x":205,
                  "y":0},
                "size":{
                  "width":80,
                  "height":18}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 父窗口 打开 数据备份",
                      "target":{
                        "targetType":"page",
                        "url":"数据备份.html",
                        "includeVariables":true},
                      "linkType":"parent"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"a8ae9b781c674cb785068fd600dd71ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.7",
            "fill":{
              "fillType":"solid",
              "color":0xFFCDE7E7},
            "location":{
              "x":111,
              "y":270},
            "size":{
              "width":798,
              "height":750}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f0395a4aa9f499a8f4070a88b1a96d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.7",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCDE7E7},
                "location":{
                  "x":111,
                  "y":270},
                "size":{
                  "width":798,
                  "height":750}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u28.png"}},
{
          "id":"e947014a16b84d2199189461e4ebcf4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":430},
            "size":{
              "width":580,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6ad92115b6e442f91a6aed920aa07a3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":430},
                "size":{
                  "width":580,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u30.png"}},
{
          "id":"99b4f9ecdc194c44bac695b8bec5e2ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":620},
            "size":{
              "width":580,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f1322d1e6f54870951c62b4b50a877f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":620},
                "size":{
                  "width":580,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u30.png"}},
{
          "id":"167f8fa6767445fa84d45fb1eaa64db4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "opacity":"0.6",
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":210,
              "y":820},
            "size":{
              "width":580,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f404e57e929d46b98c657374c299612e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "opacity":"0.6",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":210,
                  "y":820},
                "size":{
                  "width":580,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u30.png"}},
{
          "id":"5905af85deab47648355021ca48f675e",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":205,
              "y":320},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"6a67946abac04c5684d4b539ab611be3",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":1076}},
          "adaptiveStyles":{
},
          "masterId":"2bc24d6aa37f48fca27a2edc2566f219"},
{
          "id":"e520395c46804fe0812869352e06a1e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":430},
            "size":{
              "width":580,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8ad4d77a4bf4b3baed532e22de17b07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":430},
                "size":{
                  "width":580,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u93.png"}},
{
          "id":"b30f1545a84547a08daa9cc2960c2c32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":420},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bf3ec1c925a94df5b323951bed469505",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":420},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u95.png"}},
{
          "id":"a1720852ff504abbb64afb40fe5ee911",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":620},
            "size":{
              "width":580,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efe4b0c183044f6e92d9de68e5abc706",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":620},
                "size":{
                  "width":580,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u93.png"}},
{
          "id":"de3e998e6fd3464b93865a9a0b92d1a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":610},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"879732deca7a4e8ba52bf4fb0142b353",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":610},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u95.png"}},
{
          "id":"4689b60f44224e67b00593fe3d40a77c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":820},
            "size":{
              "width":580,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96007716fdde430693a783a700bb8228",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":820},
                "size":{
                  "width":580,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u93.png"}},
{
          "id":"77bd3247d8fe46418b92335dc61d026a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":810},
            "size":{
              "width":50,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18e7667c819248c99c573cd3e907613b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":810},
                "size":{
                  "width":50,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/数据备份/u95.png"}}]}},
  "masters":{
    "2bc24d6aa37f48fca27a2edc2566f219":{
      "packageId":"2bc24d6aa37f48fca27a2edc2566f219",
      "type":"Axure:Master",
      "name":"尾部-母版",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"应用字体",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"b9d9dbc456e54e4d8e0abd9bea476253",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":392,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"59080c0d83704c0ca781e25ed4e01da8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":392,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e45799983cc94366b9bb4f8c703c4194",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "location":{
                "x":362,
                "y":210},
              "size":{
                "width":30,
                "height":26}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"f57e5c6eca1544e58ea3e8ff7e56ad34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "location":{
                    "x":362,
                    "y":210},
                  "size":{
                    "width":30,
                    "height":26}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/首页-游客/u6.png"}},
{
            "id":"4deba176ee9e43789560c141124c9986",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":310,
                "y":54},
              "size":{
                "width":73,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"e7ab3558d7a24cad9d978fe12fc15f9e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":310,
                    "y":54},
                  "size":{
                    "width":73,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4d40de7299a248dabd09cef5878a0f1e",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "stateStyles":{
                "mouseOver":{
                  "textShadow":{
                    "on":true,
                    "offsetX":1,
                    "offsetY":1,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.647058823529412}},
                  "outerShadow":{
                    "on":true,
                    "offsetX":5,
                    "offsetY":5,
                    "blurRadius":5,
                    "color":{
                      "r":0,
                      "g":0,
                      "b":0,
                      "a":0.349019607843137}}},
                "mouseDown":{
                  "foreGroundFill":{
                    "fillType":"solid",
                    "color":0xFFFF0000,
                    "opacity":1}}},
              "location":{
                "x":314,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"44eb0254c92943879cacad1d8352d8a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "stateStyles":{
                    "mouseOver":{
                      "textShadow":{
                        "on":true,
                        "offsetX":1,
                        "offsetY":1,
                        "blurRadius":5,
                        "color":{
                          "r":0,
                          "g":0,
                          "b":0,
                          "a":0.647058823529412}},
                      "outerShadow":{
                        "on":true,
                        "offsetX":5,
                        "offsetY":5,
                        "blurRadius":5,
                        "color":{
                          "r":0,
                          "g":0,
                          "b":0,
                          "a":0.349019607843137}}},
                    "mouseDown":{
                      "foreGroundFill":{
                        "fillType":"solid",
                        "color":0xFFFF0000,
                        "opacity":1}}},
                  "location":{
                    "x":314,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "interactionMap":{
              "onClick":{
                "description":"OnClick",
                "cases":[{
                    "description":"用例 1",
                    "isNewIfGroup":false,
                    "actions":[{
                        "action":"linkFrame",
                        "description":"打开 美食推荐 在父窗口",
                        "linkType":"parentFrame",
                        "target":{
                          "targetType":"page",
                          "url":"美食推荐.html",
                          "includeVariables":true}}]}]}},
            "tabbable":true,
            "images":{
              "normal~":"resources/images/transparent.gif",
              "mouseOver~":"resources/images/transparent.gif",
              "mouseDown~":"resources/images/transparent.gif"}},
{
            "id":"6dcc822e1adb4096af53c02c36d3cb3b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":314,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1f79e528090e412e9e5882aaa3fe552e",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":314,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"60c82841d7054aacbf2e670de65dbeaa",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":314,
                "y":152},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"53647476ac6446df845bc73a42866610",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":314,
                    "y":152},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0c1ff6fccc464720af4e56c993bd89d7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":450,
                "y":54},
              "size":{
                "width":109,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4856d3b8fe6243848452ebbfa233f8de",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":450,
                    "y":54},
                  "size":{
                    "width":109,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"03038279fe4940c584406df1e5d06edb",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":94},
              "size":{
                "width":53,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"5431d81553824e8596db7ffc72f129ad",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":94},
                  "size":{
                    "width":53,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b84ad7cf7bf842e7a1256abb17aff0a1",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":122},
              "size":{
                "width":98,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7ceb6fa7056047c1a833a85954b9e528",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":122},
                  "size":{
                    "width":98,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ce410b98cc7945bf8614cc73c1cc88af",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":450,
                "y":152},
              "size":{
                "width":104,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"849721af33b64096bea60756168df0ce",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":450,
                    "y":152},
                  "size":{
                    "width":104,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"0b8272a768ba45248007fd9163a38922",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":632,
                "y":54},
              "size":{
                "width":86,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"4432ce471bc942ab8f1b36461fbe1b8f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":632,
                    "y":54},
                  "size":{
                    "width":86,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"858970f3895140cbba2b7764cb7b89df",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"eeb783473ff6445a94e311685a4342db",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f3b6916191894d8b81b7424d3e9045e7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"aa669e2b318041caa10ecb5ce8d87ab1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"474b1470cbf1451587e4baadbe552f35",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":632,
                "y":152},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c637fde17bcd4bd5bc986d5c86d66dec",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":632,
                    "y":152},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"f8ddfc2ca45e43928f0ecb94bb40d504",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontSize":"18px",
              "location":{
                "x":814,
                "y":54},
              "size":{
                "width":73,
                "height":22}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"079f45a243424581aa27074b6a540345",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontSize":"18px",
                  "location":{
                    "x":814,
                    "y":54},
                  "size":{
                    "width":73,
                    "height":22}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"646c844975414d0ba7ffb19e35a4fd24",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":814,
                "y":94},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"6ffb6eb232ab4ed68658a4fd03e996a8",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":814,
                    "y":94},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"7897f701f1404f0a8e0d113030524e65",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":814,
                "y":122},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"38cb138dc8754ae3b80d3ef25d025090",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":814,
                    "y":122},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"69988047564d4a0d919e20f85f024384",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":472,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"405ce975c8a548e2ba228f7ec8a28f57",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":472,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"ebf7f39846c741e2b30ca34abd559f94",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":558,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"b030ec32c43946eca2bc7113a7765a72",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":558,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"48f6d60726ce400b974fcdefb50a5da4",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":642,
                "y":214},
              "size":{
                "width":65,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"c37f2721da934703ac3f4b89684ff202",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":642,
                    "y":214},
                  "size":{
                    "width":65,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"78a2f98174e24fa7a7ca5386815c9cd7",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"16px",
              "fontWeight":"400",
              "location":{
                "x":734,
                "y":214},
              "size":{
                "width":97,
                "height":19}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"348e775cfdf242ab8fc1f78b325f5b90",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"16px",
                  "fontWeight":"400",
                  "location":{
                    "x":734,
                    "y":214},
                  "size":{
                    "width":97,
                    "height":19}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"4427c544919f48eeb68d4a1fc70fc896",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":200,
                "y":258},
              "size":{
                "width":248,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"cf758ab4dc194b1aadb7d769c5178f34",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":200,
                    "y":258},
                  "size":{
                    "width":248,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"b849ec93d5744852b6b806c12e38351b",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":486,
                "y":258},
              "size":{
                "width":145,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"786f18d4bdf2439b90764113463224cc",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":486,
                    "y":258},
                  "size":{
                    "width":145,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"e7107dfd844e4d838b4dd468406982af",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":670,
                "y":258},
              "size":{
                "width":240,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"a12ed323c09c40298ad5950c9617ffe1",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":670,
                    "y":258},
                  "size":{
                    "width":240,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"c57f4b97c75b49039a289fe069949b12",
            "label":"",
            "type":"buttonShape",
            "styleType":"h1",
            "visible":true,
            "style":{
              "fontName":"'Arial Normal', 'Arial'",
              "fontSize":"13px",
              "fontWeight":"400",
              "location":{
                "x":940,
                "y":258},
              "size":{
                "width":100,
                "height":16}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"7d340984ce3241419a70e2dbbdf6666f",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fontName":"'Arial Normal', 'Arial'",
                  "fontSize":"13px",
                  "fontWeight":"400",
                  "location":{
                    "x":940,
                    "y":258},
                  "size":{
                    "width":100,
                    "height":16}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"resources/images/transparent.gif"}},
{
            "id":"a8fc1a806536415abbaef0f5c602a689",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.8",
              "location":{
                "x":122,
                "y":30},
              "size":{
                "width":998,
                "height":10},
              "borderWidth":"4",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u250_line.png"}},
{
            "id":"eaaafc313b134f8f8524fa334162f922",
            "label":"",
            "type":"horizontalLine",
            "styleType":"horizontalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":200,
                "y":191},
              "size":{
                "width":840,
                "height":10},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u251_line.png"}},
{
            "id":"7aa4994dce524c92906c252006d25e06",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":419,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}},
{
            "id":"3996e23147554ca0b6327f6c767b2661",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":585,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}},
{
            "id":"7996e335f69441238f1d42f1eef188b1",
            "label":"",
            "type":"verticalLine",
            "styleType":"verticalLine",
            "visible":true,
            "style":{
              "opacity":"0.6",
              "location":{
                "x":759,
                "y":54},
              "size":{
                "width":10,
                "height":117},
              "borderWidth":"3",
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "images":{
              "start~":"resources/images/transparent.gif",
              "end~":"resources/images/transparent.gif",
              "line~":"images/首页-游客/u252_line.png"}}]}}},
  "objectPaths":{
    "2176af3dcc6b470aa26421769c5b75ef":{
      "scriptId":"u0"},
    "d08cece41a234f8e875e845c2870dc81":{
      "scriptId":"u1"},
    "280932a0e79f4e9590c4ba8a4501abec":{
      "scriptId":"u2"},
    "4f0a3bd116fe4436b5fe000a5c721d5b":{
      "scriptId":"u3"},
    "9b89ab49ff57434ca3f31a13a9c965fd":{
      "scriptId":"u4"},
    "94912384d2e4438aafb6fefdfd3ea6df":{
      "scriptId":"u5"},
    "b5192b38107248e79e7cd362c5258bfc":{
      "scriptId":"u6"},
    "3c8f7445edd44c5a954c6aa2a7dadf05":{
      "scriptId":"u7"},
    "3643f3c6ab734ad2ad7d779797c23b3e":{
      "scriptId":"u8"},
    "319801cc0ce543deb6f3e1caedac8648":{
      "scriptId":"u9"},
    "1fd2e35b7a354e6d83f08d9ab6d3745b":{
      "scriptId":"u10"},
    "670999e84a36439d83f2d3ed91667216":{
      "scriptId":"u11"},
    "12f2b1721bdf475eae5dde7d3526e056":{
      "scriptId":"u12"},
    "eda28cab72244b2f8c0e2c2c51983c8c":{
      "scriptId":"u13"},
    "9ae3bcaac9a3466490f9e82b739ae48e":{
      "scriptId":"u14"},
    "a009617fbaba49769851bc00a6d33aab":{
      "scriptId":"u15"},
    "9358afabecad4879a51dab02e5a54ccb":{
      "scriptId":"u16"},
    "c8325515690a442eb14910ce9ea1687a":{
      "scriptId":"u17"},
    "27c0d8e7bd1441e0926d1e0d312753ab":{
      "scriptId":"u18"},
    "2cb032d78c6a43498e895e7332b5341b":{
      "scriptId":"u19"},
    "a51752e636dd430386934d9b34ec6ca5":{
      "scriptId":"u20"},
    "9eac24f15bf348f08f28279230e338fc":{
      "scriptId":"u21"},
    "65ec34770a2d423d9995510b3cbac591":{
      "scriptId":"u22"},
    "d111526c60f34744a8c59791ee320284":{
      "scriptId":"u23"},
    "fbb65d6a4f254a7fbc190c21646eb499":{
      "scriptId":"u24"},
    "93b90080a7ff4fa7acea3ce38d74cf67":{
      "scriptId":"u25"},
    "ddf248c3d8ce4d79a32f9611f83bb581":{
      "scriptId":"u26"},
    "70136e6c00ad4c0195ea1c8a29d6235d":{
      "scriptId":"u27"},
    "a8ae9b781c674cb785068fd600dd71ae":{
      "scriptId":"u28"},
    "6f0395a4aa9f499a8f4070a88b1a96d6":{
      "scriptId":"u29"},
    "e947014a16b84d2199189461e4ebcf4c":{
      "scriptId":"u30"},
    "a6ad92115b6e442f91a6aed920aa07a3":{
      "scriptId":"u31"},
    "99b4f9ecdc194c44bac695b8bec5e2ff":{
      "scriptId":"u32"},
    "5f1322d1e6f54870951c62b4b50a877f":{
      "scriptId":"u33"},
    "167f8fa6767445fa84d45fb1eaa64db4":{
      "scriptId":"u34"},
    "f404e57e929d46b98c657374c299612e":{
      "scriptId":"u35"},
    "5905af85deab47648355021ca48f675e":{
      "scriptId":"u36"},
    "6a67946abac04c5684d4b539ab611be3":{
      "scriptId":"u37",
      "b9d9dbc456e54e4d8e0abd9bea476253":{
        "scriptId":"u38"},
      "59080c0d83704c0ca781e25ed4e01da8":{
        "scriptId":"u39"},
      "e45799983cc94366b9bb4f8c703c4194":{
        "scriptId":"u40"},
      "f57e5c6eca1544e58ea3e8ff7e56ad34":{
        "scriptId":"u41"},
      "4deba176ee9e43789560c141124c9986":{
        "scriptId":"u42"},
      "e7ab3558d7a24cad9d978fe12fc15f9e":{
        "scriptId":"u43"},
      "4d40de7299a248dabd09cef5878a0f1e":{
        "scriptId":"u44"},
      "44eb0254c92943879cacad1d8352d8a8":{
        "scriptId":"u45"},
      "6dcc822e1adb4096af53c02c36d3cb3b":{
        "scriptId":"u46"},
      "1f79e528090e412e9e5882aaa3fe552e":{
        "scriptId":"u47"},
      "60c82841d7054aacbf2e670de65dbeaa":{
        "scriptId":"u48"},
      "53647476ac6446df845bc73a42866610":{
        "scriptId":"u49"},
      "0c1ff6fccc464720af4e56c993bd89d7":{
        "scriptId":"u50"},
      "4856d3b8fe6243848452ebbfa233f8de":{
        "scriptId":"u51"},
      "03038279fe4940c584406df1e5d06edb":{
        "scriptId":"u52"},
      "5431d81553824e8596db7ffc72f129ad":{
        "scriptId":"u53"},
      "b84ad7cf7bf842e7a1256abb17aff0a1":{
        "scriptId":"u54"},
      "7ceb6fa7056047c1a833a85954b9e528":{
        "scriptId":"u55"},
      "ce410b98cc7945bf8614cc73c1cc88af":{
        "scriptId":"u56"},
      "849721af33b64096bea60756168df0ce":{
        "scriptId":"u57"},
      "0b8272a768ba45248007fd9163a38922":{
        "scriptId":"u58"},
      "4432ce471bc942ab8f1b36461fbe1b8f":{
        "scriptId":"u59"},
      "858970f3895140cbba2b7764cb7b89df":{
        "scriptId":"u60"},
      "eeb783473ff6445a94e311685a4342db":{
        "scriptId":"u61"},
      "f3b6916191894d8b81b7424d3e9045e7":{
        "scriptId":"u62"},
      "aa669e2b318041caa10ecb5ce8d87ab1":{
        "scriptId":"u63"},
      "474b1470cbf1451587e4baadbe552f35":{
        "scriptId":"u64"},
      "c637fde17bcd4bd5bc986d5c86d66dec":{
        "scriptId":"u65"},
      "f8ddfc2ca45e43928f0ecb94bb40d504":{
        "scriptId":"u66"},
      "079f45a243424581aa27074b6a540345":{
        "scriptId":"u67"},
      "646c844975414d0ba7ffb19e35a4fd24":{
        "scriptId":"u68"},
      "6ffb6eb232ab4ed68658a4fd03e996a8":{
        "scriptId":"u69"},
      "7897f701f1404f0a8e0d113030524e65":{
        "scriptId":"u70"},
      "38cb138dc8754ae3b80d3ef25d025090":{
        "scriptId":"u71"},
      "69988047564d4a0d919e20f85f024384":{
        "scriptId":"u72"},
      "405ce975c8a548e2ba228f7ec8a28f57":{
        "scriptId":"u73"},
      "ebf7f39846c741e2b30ca34abd559f94":{
        "scriptId":"u74"},
      "b030ec32c43946eca2bc7113a7765a72":{
        "scriptId":"u75"},
      "48f6d60726ce400b974fcdefb50a5da4":{
        "scriptId":"u76"},
      "c37f2721da934703ac3f4b89684ff202":{
        "scriptId":"u77"},
      "78a2f98174e24fa7a7ca5386815c9cd7":{
        "scriptId":"u78"},
      "348e775cfdf242ab8fc1f78b325f5b90":{
        "scriptId":"u79"},
      "4427c544919f48eeb68d4a1fc70fc896":{
        "scriptId":"u80"},
      "cf758ab4dc194b1aadb7d769c5178f34":{
        "scriptId":"u81"},
      "b849ec93d5744852b6b806c12e38351b":{
        "scriptId":"u82"},
      "786f18d4bdf2439b90764113463224cc":{
        "scriptId":"u83"},
      "e7107dfd844e4d838b4dd468406982af":{
        "scriptId":"u84"},
      "a12ed323c09c40298ad5950c9617ffe1":{
        "scriptId":"u85"},
      "c57f4b97c75b49039a289fe069949b12":{
        "scriptId":"u86"},
      "7d340984ce3241419a70e2dbbdf6666f":{
        "scriptId":"u87"},
      "a8fc1a806536415abbaef0f5c602a689":{
        "scriptId":"u88"},
      "eaaafc313b134f8f8524fa334162f922":{
        "scriptId":"u89"},
      "7aa4994dce524c92906c252006d25e06":{
        "scriptId":"u90"},
      "3996e23147554ca0b6327f6c767b2661":{
        "scriptId":"u91"},
      "7996e335f69441238f1d42f1eef188b1":{
        "scriptId":"u92"}},
    "e520395c46804fe0812869352e06a1e0":{
      "scriptId":"u93"},
    "a8ad4d77a4bf4b3baed532e22de17b07":{
      "scriptId":"u94"},
    "b30f1545a84547a08daa9cc2960c2c32":{
      "scriptId":"u95"},
    "bf3ec1c925a94df5b323951bed469505":{
      "scriptId":"u96"},
    "a1720852ff504abbb64afb40fe5ee911":{
      "scriptId":"u97"},
    "efe4b0c183044f6e92d9de68e5abc706":{
      "scriptId":"u98"},
    "de3e998e6fd3464b93865a9a0b92d1a8":{
      "scriptId":"u99"},
    "879732deca7a4e8ba52bf4fb0142b353":{
      "scriptId":"u100"},
    "4689b60f44224e67b00593fe3d40a77c":{
      "scriptId":"u101"},
    "96007716fdde430693a783a700bb8228":{
      "scriptId":"u102"},
    "77bd3247d8fe46418b92335dc61d026a":{
      "scriptId":"u103"},
    "18e7667c819248c99c573cd3e907613b":{
      "scriptId":"u104"}}});