$axure.loadCurrentPage({
  "url":"注册.html",
  "generationDate":new Date(1418135187830.35),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "defaultBackgroundImageInfo":{
    "path":"images/注册/bg.jpg",
    "width":1024,
    "height":682},
  "viewIdToBackgroundImageInfo":{
},
  "page":{
    "packageId":"5f6e6e4576d7450faefe460e03381b40",
    "type":"Axure:Page",
    "name":"注册",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"center",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"cover",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"setFocusOnWidget",
                "description":"设置焦点在 name 上",
                "objectPaths":[["f426ab613ff94d2b9a3523ba07b4f411"]]}]}]}},
    "diagram":{
      "objects":[{
          "id":"ab4d1ef5876a49e193d259fcd38c157f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":289.5,
              "y":140},
            "size":{
              "width":100,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b2df49abeae45df8ebb756b40a44057",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":289.5,
                  "y":140},
                "size":{
                  "width":100,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页-游客",
                      "target":{
                        "targetType":"page",
                        "url":"首页-游客.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页-游客/u6.png"}},
{
          "id":"5a8062a67fbc4d00b6d59c2c9cdda9c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":190,
              "y":320},
            "size":{
              "width":300,
              "height":210},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd18ca2645b94e38b6467a4663047b55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":190,
                  "y":320},
                "size":{
                  "width":300,
                  "height":210},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆界面/u2.png"}},
{
          "id":"09e19cc8e25e4748986eb15b153d6bf4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'楷体 Regular', '楷体'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":209,
              "y":350},
            "size":{
              "width":49,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f30417aa51794c018092a2c927a1b7b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'楷体 Regular', '楷体'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":350},
                "size":{
                  "width":49,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFocusOnWidget",
                      "description":"设置焦点在 name 上",
                      "objectPaths":[["f426ab613ff94d2b9a3523ba07b4f411"]]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4ffe93cf59a4ba98234c72662fcaae9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'楷体 Regular', '楷体'",
            "fontSize":"15px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":209,
              "y":413},
            "size":{
              "width":65,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9641997520eb424bae4e61ca6342be04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'楷体 Regular', '楷体'",
                "fontSize":"15px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":413},
                "size":{
                  "width":65,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setFocusOnWidget",
                      "description":"设置焦点在 email 上",
                      "objectPaths":[["ea80acf15a2a4a12851ca821fe8c6e7f"]]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f426ab613ff94d2b9a3523ba07b4f411",
          "label":"name",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":209,
              "y":367},
            "size":{
              "width":261,
              "height":36}},
          "adaptiveStyles":{
}},
{
          "id":"ea80acf15a2a4a12851ca821fe8c6e7f",
          "label":"email",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":209,
              "y":430},
            "size":{
              "width":261,
              "height":36}},
          "adaptiveStyles":{
}},
{
          "id":"2ddb4335f348400e834180be2fcabd95",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'楷体 Regular', '楷体'",
            "fontSize":"16px",
            "fontWeight":"400",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099CC}}},
            "fill":{
              "fillType":"solid",
              "color":0xFF00CCFF},
            "paddingTop":"3",
            "location":{
              "x":420,
              "y":476},
            "size":{
              "width":50,
              "height":24},
            "cornerRadiusTopLeft":"4"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4adaaebbea1f44a0b9daabe6060d2756",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'楷体 Regular', '楷体'",
                "fontSize":"16px",
                "fontWeight":"400",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF0099CC}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00CCFF},
                "paddingTop":"3",
                "location":{
                  "x":420,
                  "y":476},
                "size":{
                  "width":50,
                  "height":24},
                "cornerRadiusTopLeft":"4"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登陆界面/u12.png",
            "mouseOver~":"images/登陆界面/u12_mouseOver.png"}},
{
          "id":"3b5316cb13534a87a1f25ebb173872ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1}}},
            "location":{
              "x":246,
              "y":546},
            "size":{
              "width":80,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34e3c6f311254ddf83953ac89f0eb87e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099CC,
                      "opacity":1}}},
                "location":{
                  "x":246,
                  "y":546},
                "size":{
                  "width":80,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 找回密码",
                      "target":{
                        "targetType":"page",
                        "url":"找回密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"74a5bf2acdb946f389ff8ea4d98ccc0b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1}}},
            "location":{
              "x":209,
              "y":546},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17b444ac85ec4da8bff34bd8a224a17a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099CC,
                      "opacity":1}}},
                "location":{
                  "x":209,
                  "y":546},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登陆界面",
                      "target":{
                        "targetType":"page",
                        "url":"登陆界面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"6e6956ec3dcf4699bfc7771a4999f42b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":236,
              "y":540},
            "size":{
              "width":3,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9108e1aee8d4a60bc43fabfc9a694a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":236,
                  "y":540},
                "size":{
                  "width":3,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9214eacd0d6f41618b59561851f1e7a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099CC,
                  "opacity":1}}},
            "location":{
              "x":209,
              "y":572},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ef66270ce2340c2b87d4f3c2e1db326",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099CC,
                      "opacity":1}}},
                "location":{
                  "x":209,
                  "y":572},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"resources/images/transparent.gif"}},
{
          "id":"b34c2da4764f4a049491e33b09456b4b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":190,
              "y":270},
            "size":{
              "width":296,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"056961a94ebf49d296db5de0a6c2e3a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":190,
                  "y":270},
                "size":{
                  "width":296,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u20.png"}},
{
          "id":"8fe49cceb24f474a8119cb41ac714599",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF33FF00,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF00FF00},
            "location":{
              "x":190,
              "y":270},
            "size":{
              "width":5,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF00FF00}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d15199f71e084730b0093c15745baa2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF33FF00,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF00FF00},
                "location":{
                  "x":190,
                  "y":270},
                "size":{
                  "width":5,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF00FF00}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/注册/u22.png"}},
{
          "id":"354ca2015b9a449c9cea0b11750779f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":209,
              "y":480},
            "size":{
              "width":170,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dfd370d48b6484c938bc54e0ae9cb9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":209,
                  "y":480},
                "size":{
                  "width":170,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ab4d1ef5876a49e193d259fcd38c157f":{
      "scriptId":"u0"},
    "3b2df49abeae45df8ebb756b40a44057":{
      "scriptId":"u1"},
    "5a8062a67fbc4d00b6d59c2c9cdda9c3":{
      "scriptId":"u2"},
    "cd18ca2645b94e38b6467a4663047b55":{
      "scriptId":"u3"},
    "09e19cc8e25e4748986eb15b153d6bf4":{
      "scriptId":"u4"},
    "f30417aa51794c018092a2c927a1b7b5":{
      "scriptId":"u5"},
    "b4ffe93cf59a4ba98234c72662fcaae9":{
      "scriptId":"u6"},
    "9641997520eb424bae4e61ca6342be04":{
      "scriptId":"u7"},
    "f426ab613ff94d2b9a3523ba07b4f411":{
      "scriptId":"u8"},
    "ea80acf15a2a4a12851ca821fe8c6e7f":{
      "scriptId":"u9"},
    "2ddb4335f348400e834180be2fcabd95":{
      "scriptId":"u10"},
    "4adaaebbea1f44a0b9daabe6060d2756":{
      "scriptId":"u11"},
    "3b5316cb13534a87a1f25ebb173872ce":{
      "scriptId":"u12"},
    "34e3c6f311254ddf83953ac89f0eb87e":{
      "scriptId":"u13"},
    "74a5bf2acdb946f389ff8ea4d98ccc0b":{
      "scriptId":"u14"},
    "17b444ac85ec4da8bff34bd8a224a17a":{
      "scriptId":"u15"},
    "6e6956ec3dcf4699bfc7771a4999f42b":{
      "scriptId":"u16"},
    "b9108e1aee8d4a60bc43fabfc9a694a7":{
      "scriptId":"u17"},
    "9214eacd0d6f41618b59561851f1e7a8":{
      "scriptId":"u18"},
    "9ef66270ce2340c2b87d4f3c2e1db326":{
      "scriptId":"u19"},
    "b34c2da4764f4a049491e33b09456b4b":{
      "scriptId":"u20"},
    "056961a94ebf49d296db5de0a6c2e3a9":{
      "scriptId":"u21"},
    "8fe49cceb24f474a8119cb41ac714599":{
      "scriptId":"u22"},
    "d15199f71e084730b0093c15745baa2a":{
      "scriptId":"u23"},
    "354ca2015b9a449c9cea0b11750779f2":{
      "scriptId":"u24"},
    "7dfd370d48b6484c938bc54e0ae9cb9e":{
      "scriptId":"u25"}}});